### ISSUE TITLE
Morphological transformations with ropencv

### ISSUE THREAD

**Issue by ghareesh** [ropensci/opencv#18]
Hi Team..
I am using tesseract4 for doing OCR.. But it fails to read bold characters.. 
I searched opencv supporting erosion operations.. and got python equivalent..
import cv2
import numpy as np
img = cv2.imread('j.png',0)
kernel = np.ones((5,5),np.uint8)
erosion = cv2.erode(img,kernel,iterations = 1)

Not able to find same for Ropencv.. Any support on including morphological operations will be highly appreciated..

Thanks
Hareesh

**Comment by jwijffels** [comment]
You can do morphological operations like erosion with the magick package.

**Comment by ghareesh** [comment]
Ya.. I realised 5 minutes late..  Thanks for reminding..
