### ISSUE TITLE
how to link correctly?

### ISSUE THREAD

**Issue by jwijffels** [ropensci/opencv#20]
hello @jeroen 
sorry to bother you with this but I'm trying to wrap some C++ code for doing line segment detection for performing handwritten text recognition.
I'm wondering what Makevars statements I need to add to my package in order to simply do

```
#include "opencv2/imgproc.hpp"
#include "opencv2/highgui.hpp"
```

I thought simply putting LinkingTo: Rcpp, opencv in the DESCRIPTION file would work but
I'm getting on windows when compiling `Binarization.cpp` 

```
"C:/rtools40/mingw64/bin/"g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-40~1.2/include" -DNDEBUG  -I'C:/Users/Jan/Documents/R/win-library/4.0/Rcpp/include' -I'C:/Users/Jan/Documents/R/win-library/4.0/opencv/include'        -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -UNDEBUG -Wall -pedantic -g -O0 -fdiagnostics-color=always -c Binarization.cpp -o Binarization.o
E> In file included from Binarization.cpp:1
E> Binarization.hpp:6:10:fatal error: v2/imgproc.hpp: No such file or directory
```
Clearly these headers are not at C:/Users/Jan/Documents/R/win-library/4.0/Rcpp/include

Do I need to include copies of your makevars/makevars.in  and your R script in tools in my package to easily be able to do `#include "opencv2/imgproc.hpp`. Or do I just install opencv with rtools/pacman and just specify in my Requirements of the description file for CRAN that it needs opencv?

**Comment by jeroen** [comment]
> Or do I just install opencv with rtools/pacman and just specify in my Requirements of the description file for CRAN that it needs opencv?

Indeed the R package does not export the c++ library or anything like that. You would need to copy the configuration of the R package, in particular `configure`, `src/Makevars.in`, `src/Makevars.win`, and `tools/winlibs.R`.

**Comment by jwijffels** [comment]
Many thanks for the advice. Works great!

**Comment by jwijffels** [comment]
I'm fine with the setup as is (the configre script makes my life on Windows really easy - many thanks!) but maybe having a setup similar as https://github.com/swarm-lab/Rvision/blob/master/src/Makevars would allow to make this more smooth (ropensci/opencv taking care of the libs and other packages like https://github.com/DIGI-VUB/image.textlinedetector linking to it). 
Not sure if this is uberhaupt possible and allowed on CRAN to download such a large library.

**Comment by jwijffels** [comment]
Closing my own question again.
