### ISSUE TITLE
How to access cvmat_[...] and find_data_xml functions embedded in the ocv_[] functions

### ISSUE THREAD

**Issue by benyamindsmith** [ropensci/opencv#21]
Hi there, 

I know its been some time now, but I want to say that I think its very cool that you have been getting `opencv` to work with R!

**My Question:**

Beyond face recognition, I can't really do anything given the present functions available (yes, I still have alot to learn).

I was looking at some of the source code from the CRAN package version of the `ocv_face()` function and see the following:

```{r}

function (image) 
{
    facedata <- find_data_xml("haarcascades/haarcascade_frontalface_alt.xml")
    eyedata <- find_data_xml("haarcascades/haarcascade_eye_tree_eyeglasses.xml")
    cvmat_face(image, facedata, eyedata)
}

```

With the functions embedded, it looks like I can do alot more by using a custom haarcascades `.xml` file (for example, body detection) and with using an appropriate `cvmat_[...]` function.

Is there a package/source file where I can access these functions myself and tweak the functions to my liking?

I've tried Googling a little bit, but have not had much success with it.

Thanks 

Benjamin

**Comment by jeroen** [comment]
You can use the triple colon operator to access un exported functions: `opencv:::cvmat_face()`.

I think the easiest way for you to explore more functionality is to fork this package so you can work on it.

**Comment by jwijffels** [comment]
Yes. Confirming this as well. Just fork the package, write C++ code in the src folder by using the C++ API's from opencv and export the functionality you need to the R side.

**Comment by jeroen** [comment]
Of course we can merge things back in here if you like.

**Comment by benyamindsmith** [comment]
Thanks guys. 

I'll check this out. If I come up with anything interesting I will fork and merge things back.

**Comment by jeroen** [comment]
@jwijffels which is your pkg?

**Comment by jwijffels** [comment]
Working on image.textlinedetector for detecting text lines and some handwritten text recognition. Uses opencv. Haven't released it yet publicly.

**Comment by jwijffels** [comment]
@benyamindsmith I'm closing this. Feel free to reopen in case you are stuck adding opencv elements in your own package.
