### ISSUE TITLE
"/usr/share/OpenCV/haarcascades/haarcascade_frontalface_alt.xml": No such file or directory

### ISSUE THREAD

**Issue by henry090** [ropensci/opencv#24]
Hi. Could you take look at this example? @jeroen 
https://colab.research.google.com/drive/1uYfR58GZViOaoVxij5I6yTgniaqsO8zy?usp=sharing
```
Error in normalizePath(file.path(find_data_dir(), filename), mustWork = TRUE): 
path[1]="/usr/share/OpenCV/haarcascades/haarcascade_frontalface_alt.xml": No such file or directory
Traceback:

1. ocv_face(unconf)
2. find_data_xml("haarcascades/haarcascade_frontalface_alt.xml")
3. normalizePath(file.path(find_data_dir(), filename), mustWork = TRUE)
```

```
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.3 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so
```

**Comment by jeroen** [comment]
This file should be part of the `opencv-data` debian package. Can you try `apt-get install -y opencv-data`.

Perhaps this machine has a newer version of libopencv installed than what usually ships with ubuntu 18. It looks like for opencv4 the xml files now live in `usr/share/opencv4/haarcascades/

**Comment by henry090** [comment]
This worked. Thanks very much for your time and help.
