### ISSUE TITLE
Mac Install: No OpenCV 3 or newer?

### ISSUE THREAD

**Issue by dcaud** [ropensci/opencv#28]
On a mac, I do:

```
install.packages("opencv")
library(opencv)
mona <- ocv_read('https://jeroen.github.io/images/monalisa.jpg')
ocv_stylize(mona)
```

which returns

`Error in cvmat_stylize(image) : stylization requires OpenCV 3 or newer`

Any ideas?

**Comment by jeroen** [comment]
Oops that looks like a bug, one sec...

**Comment by dcaud** [comment]
I still get the same error -- presumably because CRAN doesn't have your most recent push. Can  you share code on how to install from github?

**Comment by jeroen** [comment]
Yes, getting built as we speak, one sec...

**Comment by jeroen** [comment]
Can you try with:

```r
install.packages("opencv", repos = "https://dev.ropensci.org")
```
