### ISSUE TITLE
Is there a SIFT  in this package

### ISSUE THREAD

**Issue by mytarmail** [ropensci/opencv#37]
I have read the package documentation, and did not find anything about the  SIFT  algorithm
https://cran.r-project.org/web/packages/opencv/opencv.pdf
but it is definitely in the main library
https://docs.opencv.org/4.x/da/df5/tutorial_py_sift_intro.html

_SIFT in OpenCV
Now let's see SIFT functionalities available in OpenCV. Note that these were previously only available in [the opencv contrib repo](https://github.com/opencv/opencv_contrib), but the patent expired in the year 2020. So they are now included in the main repo. Let's start with keypoint detection and draw them. First we have to construct a SIFT object. We can pass different parameters to it which are optional and they are well explained in docs._

**Comment by jwijffels** [comment]
There is currently no SIFT in the package. Wasn´t aware that the patent of it has expired? 
Do you have more proof somewhere of that patent expiration?

FYI, R package image.dlib has SURF and HOG, R package image.CornerDetectionHarris has Harris, this opencv R package has FAST and Harris

**Comment by mytarmail** [comment]
Hello! Thanks for the quick response. 
And thanks a lot for the packages listed, I didn't know about them existed.

About the evidence
_Do you have more proof somewhere of that patent expiration?_
, I just read it on the site [OpenCv](https://docs.opencv.org/4.x/da/df5/tutorial_py_sift_intro.html)
pict http://prntscr.com/a0b5VrieXmih
