### ISSUE TITLE
request opencv::ocv_qr_detect to return QR coordinates

### ISSUE THREAD

**Issue by ihellman** [ropensci/opencv#39]
Glad to see QR code scanning functionality added.  It's much faster than some other options I've found.  I'd like to request there be an option to output the coordinates of the QR code.  The 'quadrangle' package outputs topRightCorner, bottomRightAlignmentPattern, etc. which is helpful.  Thanks for all your hard work on this!

**Comment by jeroen** [comment]
OK we can do that. What would you do with this data?

**Comment by ihellman** [comment]
Great!  I've been using a QR code for scaling and orienting an image that might shift slightly between images.  For example, finding scale by finding pixel distance between topLeftCorner and topRightCorner and knowing they are 6 inches apart in real-world units.  And orientation by making the angle of the line between topLeftCorner and topRightCorner 0 degrees.  From what I can tell, it sounds like using fiducial markers like ArUco might be a better approach but I haven't found a way to detect those using R.  So I guess ultimately I'd love to see that in the R implementation of openCV.  Thanks again!

**Comment by jeroen** [comment]
You can try the new version from https://ropensci.r-universe.dev/opencv

**Comment by ihellman** [comment]
This is perfect. Thanks!
