### ISSUE TITLE
Installation error on debian 10 (buster)

### ISSUE THREAD

**Issue by mkaranja** [ropensci/opencv#41]
First of all, this is an awesome package, fast and easy to use. I look forward to many features.

I have a shiny app using opencv package and works well on my local. I would however like to deploy the app in the shiny server pro (debian) but I'm unable to install this package it. See attached screenshot of the error log.
![Screenshot from 2024-03-18 11-36-32](https://github.com/ropensci/opencv/assets/28335417/3f9ab502-c252-4d32-88d5-65301a62e0a6)

How can I fix this?

Thank you

**Comment by jeroen** [comment]
I have added a workaround for very old systems. You can install the package from https://ropensci.r-universe.dev/opencv

**Comment by mkaranja** [comment]
Successfully installed opencv. Thank you @jeroen
